package com.example.mikki.mydagger2;

import android.content.SharedPreferences;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.Toast;

import com.example.mikki.mydagger2.di.DaggerMyComponent;
import com.example.mikki.mydagger2.di.FruitModule;
import com.example.mikki.mydagger2.di.MyComponent;
import com.example.mikki.mydagger2.di.SharePreferenceModule;

import javax.inject.Inject;

public class MainActivity extends AppCompatActivity {

    //to get sharepreference object in this class
    @Inject
    SharedPreferences sharedPreferences;
    MyComponent myComponent;
    @Inject
    FruitModule fruitModule;



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //initialize myComponent
        //DaggerMyComponent is a class generated by dagger
        myComponent = DaggerMyComponent.builder()
                .sharePreferenceModule(new SharePreferenceModule(this))
                .fruitModule(new FruitModule("apple", 23))
                .build();

        //inject interface to main activity,
        //interface has to inject manually by creating method inside interface.
        myComponent.inject(this);

        Toast.makeText(this, "string: "+ fruitModule.getFruit(), Toast.LENGTH_SHORT).show();

        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putString("myKey", "hello");
        editor.apply();


    }
}
